---
name: Build with tox

'on':
  push:
    branches:
      - '!main'
      - '!gh-pages'
  pull_request: {}
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          pip install tox
      - name: Build with tox
        run: tox -e py3-build
