---
name: Deploy with tox

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install Python dependencies
        run: |
          pip install tox
      - name: Update gh-pages branch
        run: tox -e py3-ghp-import -- -m "Update site from ${{ github.sha }}"
      - name: Push gh-pages branch
        run: git push origin gh-pages
'on':
  push:
    branches:
      - main
